#!/bin/sh
#Based in polybar playerctl
set -e
playerctl status 2>/dev/null | grep -q "Playing"
apikey="$(cat $HOME/.config/polybar/.env/lastfm-key)"
apisecret="$(cat $HOME/.config/polybar/.env/lastfm-secret)"
username="$(cat $HOME/.config/polybar/.env/lastfm-username)"
password="$(cat $HOME/.config/polybar/.env/lastfm-password)"
artist="$(playerctl metadata xesam:artist)"
title="$(playerctl metadata xesam:title)"
oldTitle="$title"
oldAtist="$artist"
echo "$artist - $title"

scrobble() {
	isPlay="$(playerctl status 2>/dev/null)"
	artist="$(playerctl metadata xesam:artist)"
	title="$(playerctl metadata xesam:title)"
	scrobbleIsOn="$(cat $HOME/.config/polybar/.env/lastfm-enable)"
	if [ "$isPlay" == "Playing" ]; then
		if [ "$title" != "$oldTitle" ]; then
			if [ "$artist" != "$oldArtist" ]; then
				oldTitle="$title"
				oldAtist="$artist"
				if [ "$scrobbleIsOn" == "yes" ]; then
					echo "$artist - $title"
					node $HOME/Documents/GIT/TiagoDanin/Polybar-Lastfm/main.js "$apikey" "$apisecret" "$username" "$password" "scrobble" "$artist" "$title"
					sleep 30
				else
					echo "$artist - $title"
				fi
			fi
		fi
	else
		echo 'No Song'
		sleep 20
	fi
}
while [ true ]; do
	scrobble
	sleep 10
done
