#!/bin/sh
#Based in polybar playerctl
set -e
playerctl status 2>/dev/null | grep -q "Playing"
apikey="$(cat $HOME/.config/polybar/.env/lastfm-key)"
apisecret="$(cat $HOME/.config/polybar/.env/lastfm-secret)"
username="$(cat $HOME/.config/polybar/.env/lastfm-username)"
password="$(cat $HOME/.config/polybar/.env/lastfm-password)"
artist="$(playerctl metadata xesam:artist)"
title="$(playerctl metadata xesam:title)"
polybar-lastfm "$apikey" "$apisecret" "$username" "$password" "love" "$artist" "$title"
